
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun  6 2026 12:58:34 IST (Jun  6 2026 07:28:34 UTC)

// Verification Directory fv/dma 

module dma(axi_clk, dma_clk, rst_n, s_axi_awaddr, s_axi_awvalid,
     s_axi_awready, s_axi_wdata, s_axi_wvalid, s_axi_wready,
     s_axi_bresp, s_axi_bvalid, s_axi_bready, s_axi_araddr,
     s_axi_arvalid, s_axi_arready, s_axi_rdata, s_axi_rresp,
     s_axi_rvalid, s_axi_rready, done, irq);
  input axi_clk, dma_clk, rst_n, s_axi_awvalid, s_axi_wvalid,
       s_axi_bready, s_axi_arvalid, s_axi_rready;
  input [3:0] s_axi_awaddr, s_axi_araddr;
  input [31:0] s_axi_wdata;
  output s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready,
       s_axi_rvalid, done, irq;
  output [1:0] s_axi_bresp, s_axi_rresp;
  output [31:0] s_axi_rdata;
  wire axi_clk, dma_clk, rst_n, s_axi_awvalid, s_axi_wvalid,
       s_axi_bready, s_axi_arvalid, s_axi_rready;
  wire [3:0] s_axi_awaddr, s_axi_araddr;
  wire [31:0] s_axi_wdata;
  wire s_axi_awready, s_axi_wready, s_axi_bvalid, s_axi_arready,
       s_axi_rvalid, done, irq;
  wire [1:0] s_axi_bresp, s_axi_rresp;
  wire [31:0] s_axi_rdata;
  wire [15:0] len_s2;
  wire [4:0] u_fifo_wgray;
  wire [4:0] u_fifo_wbin;
  wire [15:0] u_dma_count;
  wire [4:0] u_fifo_rgray;
  wire [4:0] u_fifo_rbin;
  wire [1:0] u_dma_state;
  wire [15:0] length_latch;
  wire [15:0] dma_length;
  wire [4:0] u_fifo_rgray_s2;
  wire [31:0] u_regs_reg_length;
  wire [2:0] u_dma_done_cnt;
  wire [4:0] u_fifo_wgray_s2;
  wire [3:0] u_regs_raddr_lat;
  wire [4:0] u_fifo_wgray_s1;
  wire [4:0] u_fifo_rgray_s1;
  wire [15:0] len_s1;
  wire [3:0] u_regs_waddr_lat;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, active, done_s1,
       done_s2, fifo_rd_en, n_0;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_12, n_13, n_14, n_15, n_17, n_18, n_19, n_20;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_84, n_85, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_94, n_95, n_96, n_97, n_98, n_100, n_101;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_122, n_123, n_124, n_125, n_127, n_129, n_130, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_140, n_141;
  wire n_142, n_143, n_145, n_148, n_151, n_154, n_155, n_156;
  wire n_157, n_159, n_160, n_161, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_222, n_223, n_224, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_236, n_237, n_238, n_239, n_240, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_251, n_252, n_253;
  wire n_254, n_255, n_256, n_257, n_258, n_259, n_260, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_270;
  wire n_271, n_272, n_274, n_276, n_277, n_278, n_279, n_280;
  wire n_281, n_282, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_301, n_302, n_303, n_305, n_306;
  wire n_307, n_308, n_309, n_311, n_312, n_313, n_314, n_315;
  wire n_316, n_317, n_318, n_319, n_320, n_321, n_322, n_323;
  wire n_324, n_325, n_326, n_328, n_329, n_330, n_331, n_333;
  wire n_335, n_336, n_337, n_387, n_388, n_389, n_390, n_391;
  wire n_392, n_393, n_394, n_395, n_396, n_397, n_398, n_399;
  wire n_400, n_401, n_402, n_403, n_404, n_405, start_tog, stog_s1;
  wire stog_s2, stog_s3, u_regs_status_done;
  assign irq = done;
  assign s_axi_rresp[0] = 1'b0;
  assign s_axi_rresp[1] = 1'b0;
  assign s_axi_bresp[0] = 1'b0;
  assign s_axi_bresp[1] = 1'b0;
  OAI2BB2X1 g6187__2398(.A0N (len_s2[15]), .A1N (n_279), .B0 (n_208),
       .B1 (n_397), .Y (n_331));
  MXI2X1 g6220__5107(.A (n_236), .B (u_fifo_wgray[4]), .S0 (n_318), .Y
       (n_333));
  DFFRHQX4 \u_fifo_wbin_reg[3] (.RN (rst_n), .CK (axi_clk), .D (n_387),
       .Q (u_fifo_wbin[3]));
  CLKINVX1 g6233(.A (n_387), .Y (n_330));
  OAI221X1 g6189__6260(.A0 (n_288), .A1 (n_302), .B0 (n_119), .B1
       (n_323), .C0 (n_325), .Y (n_328));
  OAI222X1 g6190__8428(.A0 (u_dma_count[14]), .A1 (n_325), .B0 (n_324),
       .B1 (n_309), .C0 (n_115), .C1 (n_323), .Y (n_326));
  OAI222X1 g6213__6783(.A0 (n_168), .A1 (n_323), .B0 (n_211), .B1
       (n_315), .C0 (n_213), .C1 (n_321), .Y (n_322));
  OAI222X1 g6212__3680(.A0 (len_s2[10]), .A1 (n_323), .B0 (n_268), .B1
       (n_311), .C0 (n_256), .C1 (n_321), .Y (n_320));
  OAI222X1 g6222__1617(.A0 (n_229), .A1 (n_321), .B0 (n_227), .B1
       (n_313), .C0 (n_122), .C1 (n_323), .Y (n_319));
  NOR2BX2 g6251__2802(.AN (u_fifo_wbin[3]), .B (n_317), .Y (n_318));
  OAI222X1 g6214__1705(.A0 (n_167), .A1 (n_323), .B0 (n_212), .B1
       (n_315), .C0 (n_177), .C1 (n_321), .Y (n_316));
  OAI222X1 g6223__5122(.A0 (n_218), .A1 (n_321), .B0 (n_228), .B1
       (n_313), .C0 (n_169), .C1 (n_323), .Y (n_314));
  OAI222X1 g6211__8246(.A0 (len_s2[11]), .A1 (n_323), .B0 (n_267), .B1
       (n_311), .C0 (n_321), .C1 (n_269), .Y (n_312));
  CLKINVX1 g6259(.A (n_329), .Y (n_308));
  SDFFRHQX4 \u_fifo_wgray_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (n_274), .SE (n_307), .SI (n_271), .Q (u_fifo_wgray[0]));
  CLKINVX8 g6260(.A (n_305), .Y (n_317));
  SDFFRHQX4 \u_fifo_rgray_reg[2] (.RN (rst_n), .CK (dma_clk), .D
       (n_287), .SE (n_388), .SI (n_265), .Q (u_fifo_rgray[2]));
  OAI222X2 g6195__7098(.A0 (n_120), .A1 (n_323), .B0 (n_321), .B1
       (n_282), .C0 (n_281), .C1 (n_298), .Y (n_303));
  AOI21X2 g6196__6131(.A0 (u_dma_count[13]), .A1 (n_296), .B0 (n_301),
       .Y (n_309));
  OAI22X4 g6273__1881(.A0 (u_fifo_wbin[2]), .A1 (n_289), .B0 (n_290),
       .B1 (n_278), .Y (n_329));
  CLKINVX1 g6200(.A (n_301), .Y (n_302));
  OAI222X1 g6231__7482(.A0 (u_dma_count[0]), .A1 (n_321), .B0 (n_232),
       .B1 (n_298), .C0 (n_123), .C1 (n_323), .Y (n_299));
  OAI222X1 g6226__4733(.A0 (n_124), .A1 (n_323), .B0 (n_239), .B1
       (n_298), .C0 (n_240), .C1 (n_321), .Y (n_297));
  AOI21X2 g6240__6161(.A0 (n_151), .A1 (n_296), .B0 (n_295), .Y
       (n_315));
  AOI21X1 g6239__9315(.A0 (n_207), .A1 (n_296), .B0 (n_295), .Y
       (n_313));
  OAI222X1 g6225__9945(.A0 (n_112), .A1 (n_323), .B0 (n_248), .B1
       (n_298), .C0 (n_249), .C1 (n_321), .Y (n_294));
  OAI222X1 g6224__2883(.A0 (n_118), .A1 (n_323), .B0 (n_154), .B1
       (n_298), .C0 (n_155), .C1 (n_321), .Y (n_293));
  OAI222X1 g6218__2346(.A0 (n_129), .A1 (n_323), .B0 (n_57), .B1
       (n_298), .C0 (n_105), .C1 (n_321), .Y (n_292));
  OAI222X1 g6219__1666(.A0 (n_114), .A1 (n_323), .B0 (n_108), .B1
       (n_298), .C0 (n_133), .C1 (n_321), .Y (n_291));
  NOR2X6 g6277__7410(.A (n_290), .B (n_289), .Y (n_305));
  AOI21X2 g6241__6417(.A0 (n_243), .A1 (n_296), .B0 (n_295), .Y
       (n_311));
  MXI2X1 g6242__5477(.A (n_148), .B (u_fifo_rgray[4]), .S0 (n_398), .Y
       (n_306));
  DFFRHQX4 \u_fifo_rbin_reg[3] (.RN (rst_n), .CK (dma_clk), .D (n_388),
       .Q (u_fifo_rbin[3]));
  NAND3BX2 g6201__2398(.AN (n_321), .B (n_288), .C (n_283), .Y (n_325));
  SDFFRHQX4 \u_fifo_rgray_reg[1] (.RN (rst_n), .CK (dma_clk), .D
       (n_270), .SE (n_287), .SI (n_253), .Q (u_fifo_rgray[1]));
  CLKINVX1 g6245(.A (n_285), .Y (n_286));
  CLKINVX1 g6280(.A (n_307), .Y (n_284));
  OAI21X2 g6202__5107(.A0 (n_321), .A1 (n_283), .B0 (n_298), .Y
       (n_301));
  AOI2BB1X1 g6230__6260(.A0N (n_281), .A1N (n_266), .B0 (n_283), .Y
       (n_282));
  CLKINVX2 g6246(.A (n_298), .Y (n_295));
  OAI22X4 g6291__4319(.A0 (u_fifo_wbin[1]), .A1 (n_276), .B0 (n_277),
       .B1 (n_264), .Y (n_307));
  CLKINVX1 g6250(.A (n_388), .Y (n_280));
  AOI31X2 g6247__8428(.A0 (u_dma_state[0]), .A1 (n_263), .A2 (n_242),
       .B0 (n_279), .Y (n_285));
  CLKINVX8 g6281(.A (n_278), .Y (n_289));
  NOR2X6 g6295__5526(.A (n_277), .B (n_276), .Y (n_278));
  DFFRHQX1 u_dma_done_reg(.RN (rst_n), .CK (dma_clk), .D (n_262), .Q
       (done));
  NAND2X8 g6249__1617(.A (n_323), .B (n_321), .Y (n_298));
  INVXL g6300(.A (n_274), .Y (n_271));
  AOI2BB1X1 g6238__2802(.A0N (n_268), .A1N (n_267), .B0 (n_266), .Y
       (n_269));
  CLKINVX1 g6274(.A (n_287), .Y (n_265));
  CLKINVX1 g6254(.A (n_323), .Y (n_279));
  CLKAND2X3 g6236__1705(.A (n_281), .B (n_266), .Y (n_283));
  CLKINVX8 g6301(.A (n_264), .Y (n_276));
  MXI2X1 g6309__5122(.A (u_fifo_wbin[0]), .B (n_260), .S0 (n_259), .Y
       (n_274));
  NAND3X8 g6257__8246(.A (n_252), .B (n_263), .C (n_84), .Y (n_323));
  NAND2BXL g6261__7098(.AN (n_161), .B (n_257), .Y (n_262));
  OAI22X4 g6287__6131(.A0 (u_fifo_rbin[2]), .A1 (n_254), .B0 (n_255),
       .B1 (n_251), .Y (n_287));
  NOR2X8 g6313__1881(.A (n_260), .B (n_259), .Y (n_264));
  INVXL g6269(.A (n_257), .Y (n_258));
  NOR2X4 g6244__5115(.A (u_dma_count[11]), .B (n_256), .Y (n_266));
  NOR2X6 g6288__7482(.A (n_255), .B (n_254), .Y (n_272));
  CLKINVX1 g6292(.A (n_270), .Y (n_253));
  CLKINVX2 g6265(.A (n_321), .Y (n_296));
  AOI222X4 g6270__4733(.A0 (n_138), .A1 (n_116), .B0 (stog_s3), .B1
       (stog_s2), .C0 (n_117), .C1 (n_233), .Y (n_252));
  NAND3BX1 g6272__6161(.AN (u_dma_state[1]), .B (u_dma_state[0]), .C
       (n_400), .Y (n_257));
  CLKINVX8 g6293(.A (n_251), .Y (n_254));
  DFFRHQX4 \u_fifo_rbin_reg[0] (.RN (rst_n), .CK (dma_clk), .D (n_389),
       .Q (u_fifo_rbin[0]));
  OAI22X4 g6304__9315(.A0 (u_fifo_rbin[1]), .A1 (n_244), .B0 (n_245),
       .B1 (n_231), .Y (n_270));
  AOI2BB1X1 g6271__9945(.A0N (n_248), .A1N (n_238), .B0 (n_247), .Y
       (n_249));
  NAND2X4 g6318__2883(.A (active), .B (n_237), .Y (n_259));
  NAND2X4 g6252__2346(.A (n_268), .B (n_247), .Y (n_256));
  NAND3X8 g6268__1666(.A (n_263), .B (u_dma_state[0]), .C (n_234), .Y
       (n_321));
  INVXL g6310(.A (n_389), .Y (n_246));
  NOR2X6 g6308__7410(.A (n_245), .B (n_244), .Y (n_251));
  CLKINVX1 g6258(.A (n_247), .Y (n_243));
  CLKINVX1 g6283(.A (n_400), .Y (n_242));
  AOI2BB1X1 g6290__6417(.A0N (n_239), .A1N (n_226), .B0 (n_238), .Y
       (n_240));
  OAI211X4 g6328__5477(.A0 (n_236), .A1 (n_97), .B0 (n_98), .C0
       (n_219), .Y (n_237));
  NOR4X8 g6286__5107(.A (len_s2[13]), .B (len_s2[12]), .C (len_s2[14]),
       .D (n_223), .Y (n_233));
  CLKAND2X3 g6278__4319(.A (n_248), .B (n_238), .Y (n_247));
  SDFFRHQX4 active_reg(.RN (rst_n), .CK (axi_clk), .D (n_136), .SE
       (n_217), .SI (active), .Q (active));
  CLKINVX8 g6311(.A (n_231), .Y (n_244));
  AOI21X4 g6284__8428(.A0 (n_232), .A1 (n_224), .B0 (n_230), .Y
       (n_234));
  AOI2BB1XL g6297__5526(.A0N (n_228), .A1N (n_227), .B0 (n_226), .Y
       (n_229));
  AND2X6 g6336__6783(.A (u_fifo_rbin[0]), .B (n_220), .Y (n_231));
  CLKAND2X3 g6299__3680(.A (n_239), .B (n_226), .Y (n_238));
  NAND3X6 g6303__1617(.A (len_s2[10]), .B (len_s2[11]), .C (n_215), .Y
       (n_223));
  SDFFRHQX4 \length_latch_reg[3] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[3]), .SE (n_222), .SI (dma_length[3]), .Q
       (length_latch[3]));
  SDFFRHQX4 \length_latch_reg[4] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[4]), .SE (n_222), .SI (dma_length[4]), .Q
       (length_latch[4]));
  SDFFRHQX4 \length_latch_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[0]), .SE (n_222), .SI (dma_length[0]), .Q
       (length_latch[0]));
  SDFFRHQX4 \length_latch_reg[1] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[1]), .SE (n_222), .SI (dma_length[1]), .Q
       (length_latch[1]));
  SDFFRHQX4 \length_latch_reg[12] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[12]), .SE (n_222), .SI (dma_length[12]), .Q
       (length_latch[12]));
  SDFFRHQX4 \length_latch_reg[5] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[5]), .SE (n_222), .SI (dma_length[5]), .Q
       (length_latch[5]));
  SDFFRHQX4 \length_latch_reg[8] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[8]), .SE (n_222), .SI (dma_length[8]), .Q
       (length_latch[8]));
  SDFFRHQX4 \length_latch_reg[10] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[10]), .SE (n_222), .SI (dma_length[10]), .Q
       (length_latch[10]));
  AOI221X4 g6395__2802(.A0 (n_6), .A1 (n_48), .B0 (u_fifo_wgray[3]),
       .B1 (u_fifo_rgray_s2[3]), .C0 (n_214), .Y (n_219));
  SDFFRHQX4 \length_latch_reg[15] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[15]), .SE (n_222), .SI (dma_length[15]), .Q
       (length_latch[15]));
  SDFFRHQX4 \length_latch_reg[13] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[13]), .SE (n_222), .SI (dma_length[13]), .Q
       (length_latch[13]));
  SDFFRHQX4 \length_latch_reg[11] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[11]), .SE (n_222), .SI (dma_length[11]), .Q
       (length_latch[11]));
  SDFFRHQX4 \length_latch_reg[6] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[6]), .SE (n_222), .SI (dma_length[6]), .Q
       (length_latch[6]));
  SDFFRHQX4 \length_latch_reg[2] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[2]), .SE (n_222), .SI (dma_length[2]), .Q
       (length_latch[2]));
  SDFFRHQX4 \length_latch_reg[7] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[7]), .SE (n_222), .SI (dma_length[7]), .Q
       (length_latch[7]));
  SDFFRHQX4 \length_latch_reg[9] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[9]), .SE (n_222), .SI (dma_length[9]), .Q
       (length_latch[9]));
  SDFFRHQX4 \length_latch_reg[14] (.RN (rst_n), .CK (axi_clk), .D
       (length_latch[14]), .SE (n_222), .SI (dma_length[14]), .Q
       (length_latch[14]));
  NOR4X8 g6298__1705(.A (u_dma_count[3]), .B (u_dma_count[8]), .C
       (u_dma_count[5]), .D (n_209), .Y (n_224));
  NOR2X4 g6371__5122(.A (n_64), .B (n_230), .Y (n_220));
  NOR2BX2 g6302__8246(.AN (n_227), .B (n_218), .Y (n_226));
  NOR2X1 g6413__7098(.A (done_s2), .B (n_222), .Y (n_217));
  NAND2X2 g6305__6131(.A (n_228), .B (n_210), .Y (n_218));
  SDFFRHQX4 \u_regs_dma_length_reg[1] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[1]), .SE (n_216), .SI (dma_length[1]), .Q
       (dma_length[1]));
  SDFFRHQX4 \u_regs_dma_length_reg[3] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[3]), .SE (n_216), .SI (dma_length[3]), .Q
       (dma_length[3]));
  SDFFRHQX4 \u_regs_dma_length_reg[4] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[4]), .SE (n_216), .SI (dma_length[4]), .Q
       (dma_length[4]));
  SDFFRHQX4 \u_regs_dma_length_reg[6] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[6]), .SE (n_216), .SI (dma_length[6]), .Q
       (dma_length[6]));
  SDFFRHQX4 \u_regs_dma_length_reg[7] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[7]), .SE (n_216), .SI (dma_length[7]), .Q
       (dma_length[7]));
  SDFFRHQX4 \u_regs_dma_length_reg[8] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[8]), .SE (n_216), .SI (dma_length[8]), .Q
       (dma_length[8]));
  NOR4X8 g6316__1881(.A (len_s2[8]), .B (len_s2[7]), .C (len_s2[9]), .D
       (n_170), .Y (n_215));
  OAI21X4 g6465__5115(.A0 (n_96), .A1 (u_fifo_rgray_s2[1]), .B0
       (n_180), .Y (n_214));
  AOI2BB1X1 g6307__7482(.A0N (n_212), .A1N (n_211), .B0 (n_210), .Y
       (n_213));
  SDFFRHQX4 \u_regs_dma_length_reg[2] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[2]), .SE (n_216), .SI (dma_length[2]), .Q
       (dma_length[2]));
  SDFFRHQX4 \u_regs_dma_length_reg[14] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[14]), .SE (n_216), .SI (dma_length[14]), .Q
       (dma_length[14]));
  SDFFRHQX4 \u_regs_dma_length_reg[15] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[15]), .SE (n_216), .SI (dma_length[15]), .Q
       (dma_length[15]));
  SDFFRHQX4 \u_regs_dma_length_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[0]), .SE (n_216), .SI (dma_length[0]), .Q
       (dma_length[0]));
  SDFFRHQX4 \u_regs_dma_length_reg[11] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[11]), .SE (n_216), .SI (dma_length[11]), .Q
       (dma_length[11]));
  SDFFRHQX4 \u_regs_dma_length_reg[13] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[13]), .SE (n_216), .SI (dma_length[13]), .Q
       (dma_length[13]));
  SDFFRHQX4 \u_regs_dma_length_reg[12] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[12]), .SE (n_216), .SI (dma_length[12]), .Q
       (dma_length[12]));
  SDFFRHQX4 \u_regs_dma_length_reg[9] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[9]), .SE (n_216), .SI (dma_length[9]), .Q
       (dma_length[9]));
  SDFFRHQX4 \u_regs_dma_length_reg[5] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[5]), .SE (n_216), .SI (dma_length[5]), .Q
       (dma_length[5]));
  SDFFRHQX4 \u_regs_dma_length_reg[10] (.RN (rst_n), .CK (axi_clk), .D
       (u_regs_reg_length[10]), .SE (n_216), .SI (dma_length[10]), .Q
       (dma_length[10]));
  NOR3X6 g6427__4733(.A (n_394), .B (n_163), .C (n_130), .Y (n_230));
  DFFRHQX1 \u_regs_s_axi_rdata_reg[22] (.RN (rst_n), .CK (axi_clk), .D
       (n_164), .Q (s_axi_rdata[22]));
  DFFRHQX1 \u_regs_s_axi_rdata_reg[4] (.RN (rst_n), .CK (axi_clk), .D
       (n_160), .Q (s_axi_rdata[4]));
  DFFRHQX1 \u_regs_s_axi_rdata_reg[14] (.RN (rst_n), .CK (axi_clk), .D
       (n_175), .Q (s_axi_rdata[14]));
  DFFRHQX1 \u_regs_s_axi_rdata_reg[8] (.RN (rst_n), .CK (axi_clk), .D
       (n_166), .Q (s_axi_rdata[8]));
  DFFRHQX1 \u_regs_s_axi_rdata_reg[24] (.RN (rst_n), .CK (axi_clk), .D
       (n_176), .Q (s_axi_rdata[24]));
  DFFRHQX1 \u_regs_s_axi_rdata_reg[17] (.RN (rst_n), .CK (axi_clk), .D
       (n_165), .Q (s_axi_rdata[17]));
  DFFRHQX4 \u_dma_done_cnt_reg[1] (.RN (rst_n), .CK (dma_clk), .D
       (n_390), .Q (u_dma_done_cnt[1]));
  NAND3X6 g6315__6161(.A (n_208), .B (n_324), .C (n_159), .Y (n_209));
  CLKINVX1 g6312(.A (n_210), .Y (n_207));
  NAND3BX1 g6350__9315(.AN (n_405), .B (n_95), .C (n_156), .Y (n_206));
  DFFRHQX1 \u_regs_s_axi_rdata_reg[20] (.RN (rst_n), .CK (axi_clk), .D
       (n_172), .Q (s_axi_rdata[20]));
  DFFRHQX1 \u_regs_s_axi_rdata_reg[29] (.RN (rst_n), .CK (axi_clk), .D
       (n_173), .Q (s_axi_rdata[29]));
  OAI221X1 g6440__9945(.A0 (n_73), .A1 (n_203), .B0 (n_53), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_205));
  OAI221X1 g6428__2883(.A0 (n_71), .A1 (n_203), .B0 (n_72), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_204));
  OAI221X1 g6429__2346(.A0 (n_34), .A1 (n_203), .B0 (n_26), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_201));
  OAI221X1 g6437__1666(.A0 (n_39), .A1 (n_203), .B0 (n_31), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_200));
  OAI221X1 g6430__7410(.A0 (n_22), .A1 (n_203), .B0 (n_49), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_199));
  OAI221X1 g6439__6417(.A0 (n_40), .A1 (n_203), .B0 (n_66), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_198));
  OAI221X1 g6431__5477(.A0 (n_78), .A1 (n_203), .B0 (n_5), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_197));
  OAI221X1 g6432__2398(.A0 (n_77), .A1 (n_203), .B0 (n_27), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_196));
  OAI221X1 g6433__5107(.A0 (n_41), .A1 (n_203), .B0 (n_2), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_195));
  OAI221X1 g6434__6260(.A0 (n_23), .A1 (n_203), .B0 (n_47), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_194));
  OAI221X1 g6435__4319(.A0 (n_79), .A1 (n_203), .B0 (n_36), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_193));
  OAI221X1 g6436__8428(.A0 (n_12), .A1 (n_203), .B0 (n_19), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_192));
  SDFFRHQX4 \u_regs_reg_length_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[0]), .SE (n_191), .SI (u_regs_reg_length[0]), .Q
       (u_regs_reg_length[0]));
  DFFRHQX4 \u_dma_done_cnt_reg[0] (.RN (rst_n), .CK (dma_clk), .D
       (n_392), .Q (u_dma_done_cnt[0]));
  OAI221X1 g6404__5526(.A0 (n_55), .A1 (n_203), .B0 (n_44), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_190));
  OAI221X1 g6403__6783(.A0 (n_38), .A1 (n_203), .B0 (n_51), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_189));
  OAI221X1 g6402__3680(.A0 (n_62), .A1 (n_203), .B0 (n_0), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_188));
  OAI221X1 g6401__1617(.A0 (n_68), .A1 (n_203), .B0 (n_50), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_187));
  OAI221X1 g6438__2802(.A0 (n_35), .A1 (n_203), .B0 (n_4), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_186));
  OAI221X1 g6400__1705(.A0 (n_81), .A1 (n_203), .B0 (n_75), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_185));
  OAI221X1 g6399__5122(.A0 (n_25), .A1 (n_203), .B0 (n_7), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_184));
  OAI221X1 g6398__8246(.A0 (n_59), .A1 (n_203), .B0 (n_9), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_183));
  OAI221X1 g6397__7098(.A0 (n_80), .A1 (n_203), .B0 (n_56), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_182));
  AOI221X4 g6480__6131(.A0 (u_fifo_rgray_s2[2]), .A1 (n_67), .B0
       (n_127), .B1 (u_fifo_wgray[2]), .C0 (n_393), .Y (n_180));
  OAI221X1 g6396__1881(.A0 (n_69), .A1 (n_203), .B0 (n_28), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_179));
  OAI221X1 g6441__5115(.A0 (n_17), .A1 (n_203), .B0 (n_3), .B1
       (s_axi_arready), .C0 (n_202), .Y (n_178));
  NOR2X4 g6314__7482(.A (u_dma_count[5]), .B (n_177), .Y (n_210));
  OAI2BB2X1 g6464__4733(.A0N (s_axi_rdata[24]), .A1N (n_174), .B0
       (n_65), .B1 (n_203), .Y (n_176));
  OAI2BB2X1 g6467__6161(.A0N (s_axi_rdata[14]), .A1N (n_174), .B0
       (n_82), .B1 (n_203), .Y (n_175));
  OAI2BB2X1 g6468__9315(.A0N (s_axi_rdata[29]), .A1N (n_174), .B0
       (n_46), .B1 (n_203), .Y (n_173));
  DFFRHQX2 u_regs_dma_start_reg(.RN (rst_n), .CK (axi_clk), .D (n_403),
       .Q (n_222));
  OAI2BB2X1 g6472__9945(.A0N (s_axi_rdata[20]), .A1N (n_174), .B0
       (n_58), .B1 (n_203), .Y (n_172));
  NAND4X8 g6374__2346(.A (n_169), .B (n_168), .C (n_167), .D (n_143),
       .Y (n_170));
  OAI2BB2X1 g6475__1666(.A0N (s_axi_rdata[8]), .A1N (n_174), .B0
       (n_24), .B1 (n_203), .Y (n_166));
  OAI2BB2X1 g6476__7410(.A0N (s_axi_rdata[17]), .A1N (n_174), .B0
       (n_37), .B1 (n_203), .Y (n_165));
  OAI2BB2X1 g6477__6417(.A0N (s_axi_rdata[22]), .A1N (n_174), .B0
       (n_70), .B1 (n_203), .Y (n_164));
  OAI221X4 g6479__5477(.A0 (n_29), .A1 (u_fifo_wgray_s2[3]), .B0
       (u_fifo_rgray[3]), .B1 (n_8), .C0 (n_395), .Y (n_163));
  OAI2BB2X1 g6474__5107(.A0N (s_axi_rdata[4]), .A1N (n_174), .B0
       (n_15), .B1 (n_203), .Y (n_160));
  NOR4X8 g6325__6260(.A (u_dma_count[6]), .B (u_dma_count[2]), .C
       (u_dma_count[7]), .D (n_134), .Y (n_159));
  NAND2X4 g6317__4319(.A (n_212), .B (n_401), .Y (n_177));
  AOI2BB2X1 g6473__5526(.A0N (s_axi_arready), .A1N (n_54), .B0
       (u_regs_reg_length[0]), .B1 (n_135), .Y (n_156));
  AOI2BB1X1 g6375__6783(.A0N (n_154), .A1N (n_132), .B0 (n_401), .Y
       (n_155));
  CLKINVX6 g6478(.A (n_403), .Y (n_216));
  CLKINVX1 g6324(.A (n_401), .Y (n_151));
  SDFFRHQX4 u_regs_s_axi_rvalid_reg(.RN (rst_n), .CK (axi_clk), .D
       (n_90), .SE (n_111), .SI (s_axi_rvalid), .Q (s_axi_rvalid));
  SDFFRHQX4 u_regs_s_axi_bvalid_reg(.RN (rst_n), .CK (axi_clk), .D
       (n_88), .SE (n_110), .SI (s_axi_bvalid), .Q (s_axi_bvalid));
  CLKINVX6 g6507(.A (n_405), .Y (n_202));
  NOR4X8 g6483__8246(.A (len_s2[2]), .B (len_s2[0]), .C (len_s2[3]), .D
       (len_s2[1]), .Y (n_143));
  SDFFRHQX4 \u_regs_raddr_lat_reg[3] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_araddr[3]), .SE (n_141), .SI (u_regs_raddr_lat[3]), .Q
       (u_regs_raddr_lat[3]));
  OR2X8 g6494__7098(.A (n_13), .B (n_140), .Y (n_191));
  NAND2X1 g6508__1881(.A (n_136), .B (n_43), .Y (n_137));
  CLKINVX8 g6495(.A (n_135), .Y (n_203));
  NAND4X8 g6466__4733(.A (n_248), .B (n_212), .C (n_288), .D (n_91), .Y
       (n_134));
  AOI21X2 g6484__6161(.A0 (u_dma_count[2]), .A1 (n_94), .B0 (n_132), .Y
       (n_133));
  OAI221X4 g6512__9945(.A0 (n_20), .A1 (u_fifo_wgray_s2[0]), .B0
       (u_fifo_rgray[0]), .B1 (n_61), .C0 (n_396), .Y (n_130));
  NOR4X8 g6503__2883(.A (u_regs_raddr_lat[3]), .B (n_174), .C (n_14),
       .D (n_101), .Y (n_135));
  OAI2BB1X1 g6553__2346(.A0N (u_dma_done_cnt[1]), .A1N
       (u_dma_done_cnt[0]), .B0 (n_85), .Y (n_125));
  NAND4X8 g6513__1666(.A (n_42), .B (n_52), .C (n_76), .D (n_109), .Y
       (n_140));
  DFFRHQX4 u_regs_s_axi_wready_reg(.RN (rst_n), .CK (axi_clk), .D
       (n_402), .Q (s_axi_wready));
  CLKINVX4 g6462(.A (n_145), .Y (n_161));
  NOR2X1 g6528__7410(.A (s_axi_arready), .B (n_89), .Y (n_111));
  NOR2X1 g6560__6417(.A (n_87), .B (n_109), .Y (n_110));
  DFFRHQX4 \u_fifo_wgray_s2_reg[2] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray_s1[2]), .Q (u_fifo_wgray_s2[2]));
  DFFRHQX4 \u_fifo_wgray_s2_reg[4] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray_s1[4]), .Q (u_fifo_wgray_s2[4]));
  DFFRHQX4 \u_fifo_rgray_s2_reg[1] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray_s1[1]), .Q (u_fifo_rgray_s2[1]));
  DFFRHQX4 \u_fifo_rgray_s2_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray_s1[0]), .Q (u_fifo_rgray_s2[0]));
  CLKAND2X6 g6491__5477(.A (n_108), .B (n_104), .Y (n_132));
  CLKAND2X6 g6493__2398(.A (n_107), .B (n_92), .Y (n_145));
  CLKINVX1 g6597(.A (n_141), .Y (n_106));
  AOI21X2 g6554__5107(.A0 (u_dma_count[0]), .A1 (u_dma_count[1]), .B0
       (n_104), .Y (n_105));
  CLKINVX1 g6575(.A (n_142), .Y (n_100));
  AOI22X4 g6551__4319(.A0 (n_236), .A1 (n_97), .B0 (n_96), .B1
       (u_fifo_rgray_s2[1]), .Y (n_98));
  DFFRHQX4 \u_fifo_wgray_s2_reg[1] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray_s1[1]), .Q (u_fifo_wgray_s2[1]));
  DFFRX4 \len_s2_reg[10] (.RN (rst_n), .CK (dma_clk), .D (len_s1[10]),
       .Q (UNCONNECTED), .QN (len_s2[10]));
  DFFRX4 \len_s2_reg[11] (.RN (rst_n), .CK (dma_clk), .D (len_s1[11]),
       .Q (UNCONNECTED0), .QN (len_s2[11]));
  NAND3X1 g6552__8428(.A (u_regs_status_done), .B
       (u_regs_raddr_lat[3]), .C (s_axi_arready), .Y (n_95));
  CLKINVX1 g6504(.A (n_104), .Y (n_94));
  NOR4X8 g6511__5526(.A (u_dma_count[11]), .B (u_dma_count[10]), .C
       (u_dma_count[1]), .D (u_dma_count[12]), .Y (n_91));
  CLKINVX1 g6572(.A (n_89), .Y (n_90));
  CLKINVX1 g6573(.A (n_87), .Y (n_88));
  CLKINVX1 g6596(.A (n_92), .Y (n_85));
  NAND2X8 g6593__3680(.A (n_18), .B (n_32), .Y (n_101));
  NAND2X2 g6615__1617(.A (u_dma_state[1]), .B (n_84), .Y (n_157));
  NAND2X4 g6594__2802(.A (s_axi_awvalid), .B (n_30), .Y (n_142));
  NAND2X4 g6617__1705(.A (s_axi_arvalid), .B (n_174), .Y (n_141));
  DFFRHQX2 \len_s1_reg[8] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[8]), .Q (len_s1[8]));
  DFFRHQX2 \len_s1_reg[1] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[1]), .Q (len_s1[1]));
  DFFRHQX2 \u_fifo_wgray_s1_reg[3] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray[3]), .Q (u_fifo_wgray_s1[3]));
  DFFRHQX2 \len_s1_reg[3] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[3]), .Q (len_s1[3]));
  DFFRHQX2 \u_fifo_rgray_s1_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray[0]), .Q (u_fifo_rgray_s1[0]));
  DFFRHQX2 \len_s1_reg[7] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[7]), .Q (len_s1[7]));
  DFFRHQX2 \u_fifo_wgray_s1_reg[2] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray[2]), .Q (u_fifo_wgray_s1[2]));
  DFFRHQX2 \len_s1_reg[0] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[0]), .Q (len_s1[0]));
  DFFRHQX2 \u_fifo_wgray_s1_reg[1] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray[1]), .Q (u_fifo_wgray_s1[1]));
  DFFRHQX2 \u_fifo_rgray_s1_reg[4] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray[4]), .Q (u_fifo_rgray_s1[4]));
  DFFRHQX2 \u_fifo_wgray_s1_reg[4] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray[4]), .Q (u_fifo_wgray_s1[4]));
  DFFRHQX2 \u_fifo_wgray_s1_reg[0] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray[0]), .Q (u_fifo_wgray_s1[0]));
  DFFRHQX2 \len_s1_reg[9] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[9]), .Q (len_s1[9]));
  DFFRHQX2 \len_s1_reg[11] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[11]), .Q (len_s1[11]));
  NOR2X4 g6616__8246(.A (u_dma_done_cnt[1]), .B (u_dma_done_cnt[0]), .Y
       (n_92));
  DFFRHQX2 stog_s1_reg(.RN (rst_n), .CK (dma_clk), .D (start_tog), .Q
       (stog_s1));
  DFFRHQX2 \len_s1_reg[6] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[6]), .Q (len_s1[6]));
  DFFRHQX2 \len_s1_reg[5] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[5]), .Q (len_s1[5]));
  DFFRHQX2 \len_s1_reg[2] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[2]), .Q (len_s1[2]));
  DFFRHQX2 \len_s1_reg[12] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[12]), .Q (len_s1[12]));
  DFFRHQX2 \len_s1_reg[10] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[10]), .Q (len_s1[10]));
  DFFRHQX2 \u_fifo_rgray_s1_reg[3] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray[3]), .Q (u_fifo_rgray_s1[3]));
  DFFRHQX2 \u_fifo_rgray_s1_reg[2] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray[2]), .Q (u_fifo_rgray_s1[2]));
  DFFRHQX2 \u_fifo_rgray_s1_reg[1] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray[1]), .Q (u_fifo_rgray_s1[1]));
  DFFRHQX2 \len_s1_reg[14] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[14]), .Q (len_s1[14]));
  DFFRHQX2 \len_s1_reg[15] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[15]), .Q (len_s1[15]));
  DFFRHQX2 \len_s1_reg[4] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[4]), .Q (len_s1[4]));
  DFFRHQX2 \len_s1_reg[13] (.RN (rst_n), .CK (dma_clk), .D
       (length_latch[13]), .Q (len_s1[13]));
  CLKAND2X6 g6591__7098(.A (s_axi_bready), .B (s_axi_bvalid), .Y
       (n_87));
  CLKAND2X6 g6592__6131(.A (s_axi_wready), .B (s_axi_awready), .Y
       (n_109));
  CLKAND2X6 g6590__1881(.A (s_axi_rready), .B (s_axi_rvalid), .Y
       (n_89));
  NOR2X6 g6614__5115(.A (u_dma_count[1]), .B (u_dma_count[0]), .Y
       (n_104));
  DFFRXL done_s1_reg(.RN (rst_n), .CK (axi_clk), .D (done), .Q
       (done_s1), .QN (UNCONNECTED1));
  MXI2X1 g2(.A (n_317), .B (n_305), .S0 (u_fifo_wbin[3]), .Y (n_387));
  XOR2X4 g6943(.A (u_fifo_rbin[3]), .B (n_272), .Y (n_388));
  XOR2X4 g6944(.A (u_fifo_rbin[0]), .B (n_220), .Y (n_389));
  AND3X8 g6945(.A (n_157), .B (n_125), .C (n_161), .Y (n_390));
  OAI2BB1X4 g6946(.A0N (u_dma_done_cnt[2]), .A1N (n_85), .B0 (n_157),
       .Y (n_391));
  NOR3BX4 g6947(.AN (n_157), .B (u_dma_done_cnt[0]), .C (n_145), .Y
       (n_392));
  XOR2X4 g6948(.A (u_fifo_rgray_s2[0]), .B (u_fifo_wgray[0]), .Y
       (n_393));
  MXI2X1 g6949(.A (n_148), .B (u_fifo_rgray[4]), .S0
       (u_fifo_wgray_s2[4]), .Y (n_394));
  XNOR2X4 g6950(.A (u_fifo_wgray_s2[1]), .B (u_fifo_rgray[1]), .Y
       (n_395));
  XNOR2X4 g6951(.A (u_fifo_rgray[2]), .B (u_fifo_wgray_s2[2]), .Y
       (n_396));
  DFFRX4 stog_s3_reg(.RN (rst_n), .CK (dma_clk), .D (stog_s2), .Q
       (stog_s3), .QN (n_138));
  DFFRX4 \len_s2_reg[1] (.RN (rst_n), .CK (dma_clk), .D (len_s1[1]), .Q
       (len_s2[1]), .QN (n_129));
  DFFRX4 \u_fifo_rgray_s2_reg[2] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray_s1[2]), .Q (u_fifo_rgray_s2[2]), .QN (n_127));
  DFFRX4 \len_s2_reg[8] (.RN (rst_n), .CK (dma_clk), .D (len_s1[8]), .Q
       (len_s2[8]), .QN (n_124));
  DFFRX4 \len_s2_reg[0] (.RN (rst_n), .CK (dma_clk), .D (len_s1[0]), .Q
       (len_s2[0]), .QN (n_123));
  DFFRX4 \len_s2_reg[7] (.RN (rst_n), .CK (dma_clk), .D (len_s1[7]), .Q
       (len_s2[7]), .QN (n_122));
  DFFRX4 \len_s2_reg[12] (.RN (rst_n), .CK (dma_clk), .D (len_s1[12]),
       .Q (len_s2[12]), .QN (n_120));
  DFFRX4 \len_s2_reg[13] (.RN (rst_n), .CK (dma_clk), .D (len_s1[13]),
       .Q (len_s2[13]), .QN (n_119));
  DFFRX4 \len_s2_reg[3] (.RN (rst_n), .CK (dma_clk), .D (len_s1[3]), .Q
       (len_s2[3]), .QN (n_118));
  DFFRX4 \len_s2_reg[15] (.RN (rst_n), .CK (dma_clk), .D (len_s1[15]),
       .Q (len_s2[15]), .QN (n_117));
  DFFRX4 stog_s2_reg(.RN (rst_n), .CK (dma_clk), .D (stog_s1), .Q
       (stog_s2), .QN (n_116));
  DFFRX4 \len_s2_reg[14] (.RN (rst_n), .CK (dma_clk), .D (len_s1[14]),
       .Q (len_s2[14]), .QN (n_115));
  DFFRX4 \len_s2_reg[2] (.RN (rst_n), .CK (dma_clk), .D (len_s1[2]), .Q
       (len_s2[2]), .QN (n_114));
  DFFRX4 \len_s2_reg[9] (.RN (rst_n), .CK (dma_clk), .D (len_s1[9]), .Q
       (len_s2[9]), .QN (n_112));
  DFFRX4 \len_s2_reg[5] (.RN (rst_n), .CK (dma_clk), .D (len_s1[5]), .Q
       (n_337), .QN (n_168));
  DFFRX4 \len_s2_reg[4] (.RN (rst_n), .CK (dma_clk), .D (len_s1[4]), .Q
       (n_336), .QN (n_167));
  DFFRX4 \len_s2_reg[6] (.RN (rst_n), .CK (dma_clk), .D (len_s1[6]), .Q
       (n_335), .QN (n_169));
  DFFRX4 done_s2_reg(.RN (rst_n), .CK (axi_clk), .D (done_s1), .Q
       (done_s2), .QN (n_136));
  SDFFRX4 \u_regs_reg_length_reg[14] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[14]), .SE (n_191), .SI (u_regs_reg_length[14]), .Q
       (u_regs_reg_length[14]), .QN (n_82));
  SDFFRX4 \u_regs_reg_length_reg[9] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[9]), .SE (n_191), .SI (u_regs_reg_length[9]), .Q
       (u_regs_reg_length[9]), .QN (n_81));
  SDFFRX4 \u_regs_reg_length_reg[7] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[7]), .SE (n_191), .SI (u_regs_reg_length[7]), .Q
       (u_regs_reg_length[7]), .QN (n_80));
  SDFFRX4 \u_regs_reg_length_reg[5] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[5]), .SE (n_191), .SI (u_regs_reg_length[5]), .Q
       (u_regs_reg_length[5]), .QN (n_79));
  SDFFRX4 \u_regs_reg_length_reg[18] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[18]), .SE (n_191), .SI (u_regs_reg_length[18]), .Q
       (u_regs_reg_length[18]), .QN (n_78));
  SDFFRX4 \u_regs_reg_length_reg[1] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[1]), .SE (n_191), .SI (u_regs_reg_length[1]), .Q
       (u_regs_reg_length[1]), .QN (n_77));
  SDFFRX4 \u_regs_waddr_lat_reg[3] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_awaddr[3]), .SE (n_142), .SI (u_regs_waddr_lat[3]), .Q
       (u_regs_waddr_lat[3]), .QN (n_76));
  DFFRX4 \u_regs_s_axi_rdata_reg[9] (.RN (rst_n), .CK (axi_clk), .D
       (n_185), .Q (s_axi_rdata[9]), .QN (n_75));
  SDFFRX4 \u_regs_reg_length_reg[19] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[19]), .SE (n_191), .SI (u_regs_reg_length[19]), .Q
       (u_regs_reg_length[19]), .QN (n_73));
  DFFRX4 \u_regs_s_axi_rdata_reg[23] (.RN (rst_n), .CK (axi_clk), .D
       (n_204), .Q (s_axi_rdata[23]), .QN (n_72));
  SDFFRX4 \u_regs_reg_length_reg[23] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[23]), .SE (n_191), .SI (u_regs_reg_length[23]), .Q
       (u_regs_reg_length[23]), .QN (n_71));
  SDFFRX4 \u_regs_reg_length_reg[22] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[22]), .SE (n_191), .SI (u_regs_reg_length[22]), .Q
       (u_regs_reg_length[22]), .QN (n_70));
  SDFFRX4 \u_regs_reg_length_reg[21] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[21]), .SE (n_191), .SI (u_regs_reg_length[21]), .Q
       (u_regs_reg_length[21]), .QN (n_69));
  SDFFRX4 \u_regs_reg_length_reg[28] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[28]), .SE (n_191), .SI (u_regs_reg_length[28]), .Q
       (u_regs_reg_length[28]), .QN (n_68));
  SDFFRX4 \u_fifo_wgray_reg[2] (.RN (rst_n), .CK (axi_clk), .D (n_329),
       .SE (n_387), .SI (n_308), .Q (u_fifo_wgray[2]), .QN (n_67));
  DFFRX4 \u_regs_s_axi_rdata_reg[16] (.RN (rst_n), .CK (axi_clk), .D
       (n_198), .Q (s_axi_rdata[16]), .QN (n_66));
  SDFFRX4 \u_regs_reg_length_reg[24] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[24]), .SE (n_191), .SI (u_regs_reg_length[24]), .Q
       (u_regs_reg_length[24]), .QN (n_65));
  DFFRX4 u_dma_fifo_rd_en_reg(.RN (rst_n), .CK (dma_clk), .D (n_399),
       .Q (fifo_rd_en), .QN (n_64));
  SDFFRX4 start_tog_reg(.RN (rst_n), .CK (axi_clk), .D (start_tog), .SE
       (n_222), .SI (n_63), .Q (start_tog), .QN (n_63));
  SDFFRX4 \u_regs_reg_length_reg[15] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[15]), .SE (n_191), .SI (u_regs_reg_length[15]), .Q
       (u_regs_reg_length[15]), .QN (n_62));
  DFFRX4 \u_fifo_wgray_s2_reg[0] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray_s1[0]), .Q (u_fifo_wgray_s2[0]), .QN (n_61));
  SDFFRX4 \u_regs_reg_length_reg[31] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[31]), .SE (n_191), .SI (u_regs_reg_length[31]), .Q
       (u_regs_reg_length[31]), .QN (n_59));
  SDFFRX4 \u_regs_reg_length_reg[20] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[20]), .SE (n_191), .SI (u_regs_reg_length[20]), .Q
       (u_regs_reg_length[20]), .QN (n_58));
  DFFRX4 \u_dma_count_reg[1] (.RN (rst_n), .CK (dma_clk), .D (n_292),
       .Q (u_dma_count[1]), .QN (n_57));
  DFFRX4 \u_regs_s_axi_rdata_reg[7] (.RN (rst_n), .CK (axi_clk), .D
       (n_182), .Q (s_axi_rdata[7]), .QN (n_56));
  SDFFRX4 \u_regs_reg_length_reg[25] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[25]), .SE (n_191), .SI (u_regs_reg_length[25]), .Q
       (u_regs_reg_length[25]), .QN (n_55));
  DFFRX4 \u_regs_s_axi_rdata_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (n_206), .Q (s_axi_rdata[0]), .QN (n_54));
  DFFRX4 \u_regs_s_axi_rdata_reg[19] (.RN (rst_n), .CK (axi_clk), .D
       (n_205), .Q (s_axi_rdata[19]), .QN (n_53));
  SDFFRX4 \u_regs_waddr_lat_reg[1] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_awaddr[1]), .SE (n_142), .SI (u_regs_waddr_lat[1]), .Q
       (u_regs_waddr_lat[1]), .QN (n_52));
  DFFRX4 \u_regs_s_axi_rdata_reg[27] (.RN (rst_n), .CK (axi_clk), .D
       (n_189), .Q (s_axi_rdata[27]), .QN (n_51));
  DFFRX4 \u_regs_s_axi_rdata_reg[28] (.RN (rst_n), .CK (axi_clk), .D
       (n_187), .Q (s_axi_rdata[28]), .QN (n_50));
  DFFRX4 \u_regs_s_axi_rdata_reg[26] (.RN (rst_n), .CK (axi_clk), .D
       (n_199), .Q (s_axi_rdata[26]), .QN (n_49));
  DFFRX4 \u_fifo_rgray_s2_reg[3] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray_s1[3]), .Q (u_fifo_rgray_s2[3]), .QN (n_48));
  DFFRX4 \u_regs_s_axi_rdata_reg[3] (.RN (rst_n), .CK (axi_clk), .D
       (n_194), .Q (s_axi_rdata[3]), .QN (n_47));
  SDFFRX4 \u_regs_reg_length_reg[29] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[29]), .SE (n_191), .SI (u_regs_reg_length[29]), .Q
       (u_regs_reg_length[29]), .QN (n_46));
  DFFRX4 \u_regs_s_axi_rdata_reg[25] (.RN (rst_n), .CK (axi_clk), .D
       (n_190), .Q (s_axi_rdata[25]), .QN (n_44));
  DFFRX4 u_regs_status_done_reg(.RN (rst_n), .CK (axi_clk), .D (n_137),
       .Q (u_regs_status_done), .QN (n_43));
  SDFFRX4 \u_regs_waddr_lat_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_awaddr[0]), .SE (n_142), .SI (u_regs_waddr_lat[0]), .Q
       (u_regs_waddr_lat[0]), .QN (n_42));
  DFFRX4 \u_dma_state_reg[0] (.RN (rst_n), .CK (dma_clk), .D (n_286),
       .Q (u_dma_state[0]), .QN (n_84));
  DFFRX4 \u_fifo_wbin_reg[1] (.RN (rst_n), .CK (axi_clk), .D (n_307),
       .Q (u_fifo_wbin[1]), .QN (n_277));
  DFFRX4 \u_fifo_rbin_reg[1] (.RN (rst_n), .CK (dma_clk), .D (n_270),
       .Q (u_fifo_rbin[1]), .QN (n_245));
  DFFRX4 \u_dma_count_reg[3] (.RN (rst_n), .CK (dma_clk), .D (n_293),
       .Q (u_dma_count[3]), .QN (n_154));
  DFFRX4 \u_fifo_rbin_reg[4] (.RN (rst_n), .CK (dma_clk), .D (n_306),
       .Q (u_fifo_rgray[4]), .QN (n_148));
  DFFRX4 \u_fifo_wbin_reg[0] (.RN (rst_n), .CK (axi_clk), .D (n_274),
       .Q (u_fifo_wbin[0]), .QN (n_260));
  DFFRX4 \u_dma_count_reg[14] (.RN (rst_n), .CK (dma_clk), .D (n_326),
       .Q (u_dma_count[14]), .QN (n_324));
  DFFRX4 \u_dma_count_reg[7] (.RN (rst_n), .CK (dma_clk), .D (n_319),
       .Q (u_dma_count[7]), .QN (n_227));
  DFFRX4 \u_dma_count_reg[13] (.RN (rst_n), .CK (dma_clk), .D (n_328),
       .Q (u_dma_count[13]), .QN (n_288));
  DFFRX4 \u_dma_count_reg[10] (.RN (rst_n), .CK (dma_clk), .D (n_320),
       .Q (u_dma_count[10]), .QN (n_268));
  DFFRX4 \u_dma_count_reg[0] (.RN (rst_n), .CK (dma_clk), .D (n_299),
       .Q (u_dma_count[0]), .QN (n_232));
  DFFRX4 \u_dma_state_reg[1] (.RN (rst_n), .CK (dma_clk), .D (n_258),
       .Q (u_dma_state[1]), .QN (n_263));
  DFFRX4 \u_dma_count_reg[4] (.RN (rst_n), .CK (dma_clk), .D (n_316),
       .Q (u_dma_count[4]), .QN (n_212));
  DFFRX4 u_regs_s_axi_arready_reg(.RN (rst_n), .CK (axi_clk), .D
       (n_106), .Q (s_axi_arready), .QN (n_174));
  SDFFRX4 \u_regs_reg_length_reg[2] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[2]), .SE (n_191), .SI (u_regs_reg_length[2]), .Q
       (u_regs_reg_length[2]), .QN (n_41));
  SDFFRX4 \u_regs_reg_length_reg[16] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[16]), .SE (n_191), .SI (u_regs_reg_length[16]), .Q
       (u_regs_reg_length[16]), .QN (n_40));
  SDFFRX4 \u_regs_reg_length_reg[11] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[11]), .SE (n_191), .SI (u_regs_reg_length[11]), .Q
       (u_regs_reg_length[11]), .QN (n_39));
  SDFFRX4 \u_regs_reg_length_reg[27] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[27]), .SE (n_191), .SI (u_regs_reg_length[27]), .Q
       (u_regs_reg_length[27]), .QN (n_38));
  SDFFRX4 \u_regs_reg_length_reg[17] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[17]), .SE (n_191), .SI (u_regs_reg_length[17]), .Q
       (u_regs_reg_length[17]), .QN (n_37));
  DFFRX4 \u_regs_s_axi_rdata_reg[5] (.RN (rst_n), .CK (axi_clk), .D
       (n_193), .Q (s_axi_rdata[5]), .QN (n_36));
  SDFFRX4 \u_regs_reg_length_reg[13] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[13]), .SE (n_191), .SI (u_regs_reg_length[13]), .Q
       (u_regs_reg_length[13]), .QN (n_35));
  SDFFRX4 \u_regs_reg_length_reg[12] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[12]), .SE (n_191), .SI (u_regs_reg_length[12]), .Q
       (u_regs_reg_length[12]), .QN (n_34));
  SDFFRX4 \u_regs_raddr_lat_reg[1] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_araddr[1]), .SE (n_141), .SI (u_regs_raddr_lat[1]), .Q
       (u_regs_raddr_lat[1]), .QN (n_32));
  DFFRX4 \u_regs_s_axi_rdata_reg[11] (.RN (rst_n), .CK (axi_clk), .D
       (n_200), .Q (s_axi_rdata[11]), .QN (n_31));
  DFFRX4 u_regs_s_axi_awready_reg(.RN (rst_n), .CK (axi_clk), .D
       (n_100), .Q (s_axi_awready), .QN (n_30));
  SDFFRX4 \u_fifo_rgray_reg[3] (.RN (rst_n), .CK (dma_clk), .D (n_388),
       .SE (n_306), .SI (n_280), .Q (u_fifo_rgray[3]), .QN (n_29));
  DFFRX4 \u_regs_s_axi_rdata_reg[21] (.RN (rst_n), .CK (axi_clk), .D
       (n_179), .Q (s_axi_rdata[21]), .QN (n_28));
  DFFRX4 \u_regs_s_axi_rdata_reg[1] (.RN (rst_n), .CK (axi_clk), .D
       (n_196), .Q (s_axi_rdata[1]), .QN (n_27));
  DFFRX4 \u_regs_s_axi_rdata_reg[12] (.RN (rst_n), .CK (axi_clk), .D
       (n_201), .Q (s_axi_rdata[12]), .QN (n_26));
  SDFFRX4 \u_regs_reg_length_reg[10] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[10]), .SE (n_191), .SI (u_regs_reg_length[10]), .Q
       (u_regs_reg_length[10]), .QN (n_25));
  SDFFRX4 \u_regs_reg_length_reg[8] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[8]), .SE (n_191), .SI (u_regs_reg_length[8]), .Q
       (u_regs_reg_length[8]), .QN (n_24));
  SDFFRX4 \u_regs_reg_length_reg[3] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[3]), .SE (n_191), .SI (u_regs_reg_length[3]), .Q
       (u_regs_reg_length[3]), .QN (n_23));
  SDFFRX4 \u_regs_reg_length_reg[26] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[26]), .SE (n_191), .SI (u_regs_reg_length[26]), .Q
       (u_regs_reg_length[26]), .QN (n_22));
  SDFFRX4 \u_fifo_rgray_reg[0] (.RN (rst_n), .CK (dma_clk), .D (n_389),
       .SE (n_270), .SI (n_246), .Q (u_fifo_rgray[0]), .QN (n_20));
  DFFRX4 \u_regs_s_axi_rdata_reg[6] (.RN (rst_n), .CK (axi_clk), .D
       (n_192), .Q (s_axi_rdata[6]), .QN (n_19));
  SDFFRX4 \u_regs_raddr_lat_reg[0] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_araddr[0]), .SE (n_141), .SI (u_regs_raddr_lat[0]), .Q
       (u_regs_raddr_lat[0]), .QN (n_18));
  SDFFRX4 \u_regs_reg_length_reg[30] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[30]), .SE (n_191), .SI (u_regs_reg_length[30]), .Q
       (u_regs_reg_length[30]), .QN (n_17));
  SDFFRX4 \u_regs_reg_length_reg[4] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[4]), .SE (n_191), .SI (u_regs_reg_length[4]), .Q
       (u_regs_reg_length[4]), .QN (n_15));
  SDFFRX4 \u_regs_raddr_lat_reg[2] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_araddr[2]), .SE (n_141), .SI (u_regs_raddr_lat[2]), .Q
       (u_regs_raddr_lat[2]), .QN (n_14));
  SDFFRX4 \u_regs_waddr_lat_reg[2] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_awaddr[2]), .SE (n_142), .SI (u_regs_waddr_lat[2]), .Q
       (u_regs_waddr_lat[2]), .QN (n_13));
  SDFFRX4 \u_regs_reg_length_reg[6] (.RN (rst_n), .CK (axi_clk), .D
       (s_axi_wdata[6]), .SE (n_191), .SI (u_regs_reg_length[6]), .Q
       (u_regs_reg_length[6]), .QN (n_12));
  DFFRX4 \u_regs_s_axi_rdata_reg[31] (.RN (rst_n), .CK (axi_clk), .D
       (n_183), .Q (s_axi_rdata[31]), .QN (n_9));
  DFFRX4 \u_fifo_wgray_s2_reg[3] (.RN (rst_n), .CK (dma_clk), .D
       (u_fifo_wgray_s1[3]), .Q (u_fifo_wgray_s2[3]), .QN (n_8));
  DFFRX4 \u_regs_s_axi_rdata_reg[10] (.RN (rst_n), .CK (axi_clk), .D
       (n_184), .Q (s_axi_rdata[10]), .QN (n_7));
  SDFFRX4 \u_fifo_wgray_reg[3] (.RN (rst_n), .CK (axi_clk), .D (n_387),
       .SE (n_333), .SI (n_330), .Q (u_fifo_wgray[3]), .QN (n_6));
  DFFRX4 \u_regs_s_axi_rdata_reg[18] (.RN (rst_n), .CK (axi_clk), .D
       (n_197), .Q (s_axi_rdata[18]), .QN (n_5));
  DFFRX4 \u_regs_s_axi_rdata_reg[13] (.RN (rst_n), .CK (axi_clk), .D
       (n_186), .Q (s_axi_rdata[13]), .QN (n_4));
  DFFRX4 \u_regs_s_axi_rdata_reg[30] (.RN (rst_n), .CK (axi_clk), .D
       (n_178), .Q (s_axi_rdata[30]), .QN (n_3));
  DFFRX4 \u_regs_s_axi_rdata_reg[2] (.RN (rst_n), .CK (axi_clk), .D
       (n_195), .Q (s_axi_rdata[2]), .QN (n_2));
  DFFRX4 \u_regs_s_axi_rdata_reg[15] (.RN (rst_n), .CK (axi_clk), .D
       (n_188), .Q (s_axi_rdata[15]), .QN (n_0));
  SDFFRX4 \u_fifo_wgray_reg[1] (.RN (rst_n), .CK (axi_clk), .D (n_307),
       .SE (n_329), .SI (n_284), .Q (u_fifo_wgray[1]), .QN (n_96));
  DFFRX4 \u_fifo_rgray_s2_reg[4] (.RN (rst_n), .CK (axi_clk), .D
       (u_fifo_rgray_s1[4]), .Q (u_fifo_rgray_s2[4]), .QN (n_97));
  DFFRX4 \u_fifo_wbin_reg[2] (.RN (rst_n), .CK (axi_clk), .D (n_329),
       .Q (u_fifo_wbin[2]), .QN (n_290));
  DFFRX4 \u_dma_count_reg[2] (.RN (rst_n), .CK (dma_clk), .D (n_291),
       .Q (u_dma_count[2]), .QN (n_108));
  DFFRX4 \u_dma_count_reg[11] (.RN (rst_n), .CK (dma_clk), .D (n_312),
       .Q (u_dma_count[11]), .QN (n_267));
  DFFRX4 \u_dma_done_cnt_reg[2] (.RN (rst_n), .CK (dma_clk), .D
       (n_391), .Q (u_dma_done_cnt[2]), .QN (n_107));
  DFFRX4 \u_dma_count_reg[5] (.RN (rst_n), .CK (dma_clk), .D (n_322),
       .Q (u_dma_count[5]), .QN (n_211));
  DFFRX4 \u_fifo_rbin_reg[2] (.RN (rst_n), .CK (dma_clk), .D (n_287),
       .Q (u_fifo_rbin[2]), .QN (n_255));
  DFFRX4 \u_dma_count_reg[15] (.RN (rst_n), .CK (dma_clk), .D (n_331),
       .Q (u_dma_count[15]), .QN (n_208));
  DFFRX4 \u_dma_count_reg[12] (.RN (rst_n), .CK (dma_clk), .D (n_303),
       .Q (u_dma_count[12]), .QN (n_281));
  DFFRX4 \u_fifo_wbin_reg[4] (.RN (rst_n), .CK (axi_clk), .D (n_333),
       .Q (u_fifo_wgray[4]), .QN (n_236));
  DFFRX4 \u_dma_count_reg[8] (.RN (rst_n), .CK (dma_clk), .D (n_297),
       .Q (u_dma_count[8]), .QN (n_239));
  DFFRX4 \u_dma_count_reg[6] (.RN (rst_n), .CK (dma_clk), .D (n_314),
       .Q (u_dma_count[6]), .QN (n_228));
  DFFRX4 \u_dma_count_reg[9] (.RN (rst_n), .CK (dma_clk), .D (n_294),
       .Q (u_dma_count[9]), .QN (n_248));
  OA21X4 g7192(.A0 (n_324), .A1 (n_321), .B0 (n_309), .Y (n_397));
  CLKAND2X12 g7193(.A (u_fifo_rbin[3]), .B (n_272), .Y (n_398));
  NOR2BX4 g7194(.AN (n_234), .B (n_285), .Y (n_399));
  NOR3BX4 g7195(.AN (n_224), .B (n_232), .C (n_230), .Y (n_400));
  NOR2BX4 g7196(.AN (n_132), .B (u_dma_count[3]), .Y (n_401));
  NOR2BX4 g7197(.AN (s_axi_wvalid), .B (s_axi_wready), .Y (n_402));
  NOR3BX4 g7198(.AN (s_axi_wdata[0]), .B (u_regs_waddr_lat[2]), .C
       (n_140), .Y (n_403));
  NOR2X8 g7199(.A (n_404), .B (n_174), .Y (n_405));
  AOI21X4 g3(.A0 (u_regs_raddr_lat[2]), .A1 (u_regs_raddr_lat[3]), .B0
       (n_101), .Y (n_404));
endmodule

