read_physical -lef {/home/install/FOUNDRY/digital/45nm/dig/lef/gsclib045_tech.lef /home/install/FOUNDRY/digital/45nm/dig/lef/gsclib045_macro.lef}
read_netlist /home/vlsi/vvr/project/dma_netlist.v -top dma
read_timing /home/install/FOUNDRY/digital/45nm/dig/lib/slow.lib
init_design
